function myFunction() {
  var x = document.getElementById("myText").value;
  document.getElementById("demo");

switch(x) {
  case "st.dwi89@gmail.com":
    // SERVER 1 SIJA 
    // window.location.replace("https://edu1smkn1cmh.gnomio.com");
    window.location.replace("https://lh3.googleusercontent.com/proxy/Xwemiuxj8k9L3FH8GJg5HGt3ChaaWUQg6ufdB01WaA4KoOi039-XwUXHFXY1eb5sdwZdPAc2tZWBCIJcVq-ItQXMiXOUsk2gUCoeK4wejpAcIZL7wTuoMPm1uwVpzqR-zUki");
    break;
 
  case "gurukeren99@gmail.com":
    // SERVER 2 RPL
    // window.location.replace("https://edu2smkn1cmh.gnomio.com");    
    window.location.replace("https://lh3.googleusercontent.com/proxy/KToG_95aGjO8zoTqMmybqR9pqUO-_J4-appSBdPAwrEid6hGcAIqQGwC-1Q4kRmm_nJqjOQRbigMN67eEgLNYBBQqbaIdoPApimk8UbmBhFtoFYOKEy6kD6BV4Sx7xoDlvUgHi_wF9qzTPqJqiY"); 
    break;

case "palimbongpither@gmail.com": document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, PITHER PALIMBONG Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "hendradermawan31@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, HENDRA DERMAWAN Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "nangsuh@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, NANANG SUHARYA, S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "sriw3389@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, SRI WULAN NURHAWATI, S.PD. Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "euisnia23567@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, EUIS KURNIA SETIAWATI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "linesyafa@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, LINA SYAFA'AH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "muhammadimsak74@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, MUHAMMAD IMSAK, S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "resmana_yuyun@yahoo.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, YUYUN RESMANA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "budiwijaya07@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, BUDI WIJAYA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "lenimuharoh85@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, LENI MUHAROH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "fitriyusmaniah@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, FITRI YUSMANIAH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "niaayundafarah2@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, KURNIA DEWI ARYANI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "jusnainisaade@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, HJ JUSNAINI,SPD,M.PD Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "gurukusuminah@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, SUMINAH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "marnilestarina7776@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, MARNI LESTARINA,S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "kurniasari.bagus@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, NIA KURNIASARI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "fikihman2@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ILYAS HABIBI, S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "sitimuthmainnahnfr@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, SITI MUTHMAINNAH.S.PD Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "tania.sendratari@yahoo.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, TANIA SENDRATARI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "asrinisuroso11@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ASRINIYATUN Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "muhimanm78@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, M.  IMAN M Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "niningpermanaputra@yahoo.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, NINING DWI KARWATI, S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "nandriyani87@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, NURLIA ANDRIYANI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "hamidahks@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, HAMIDAH KUNTARI SUPROBO, S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "shan_anugerah@yahoo.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, MOH INSAN BUDIMAN Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "anggraeni.saptia717@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ANGGRAENI SAPTIA ARIATI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "diantardiah6626@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, DRA. DIAN TARDIAH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "phutzalone@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, FITRI AGUSTINE Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "wulantika19850209@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, RIDHA WULANTIKA ROSMAN, S.PD Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "ahmades669@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, AHMAD SARIPUDIN  Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "ulums.17@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, M. SAIFUL ULUM, S.PD.I Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "muflihatimeli87@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, MELI MUFLIHATI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "purwati.ipur83@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, PURWATI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "adunmukholadun70@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Mohon maaf, ADUN MUKHOLADUN MUKHOLADUN Anda dinyatakan</p><p style='font-size:20px ; color:red'>TIDAK LULUS</p>"; break;
case "agusrianti.17agust@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Mohon maaf, AGUSRIANTI AGUSRIANTI Anda dinyatakan</p><p style='font-size:20px ; color:red'>TIDAK LULUS</p>"; break;
case "mfarhansatrian0@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Mohon maaf, M FARHAN SATRIA N Anda dinyatakan</p><p style='font-size:20px ; color:red'>TIDAK LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "asepsukanta44@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ASEP SUKANTA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "cucumcuminar@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, CUCUM CUMINAR Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "linaferaherliana@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, LINA FERA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "srilestarisupriadi68@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, SRI LESTARI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "kartiwi300@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, WIKA KARTIWI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "aantriono82@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, AAN TRIONO Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "asmul.mikayla35@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ASEP MULYANA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "cisay.mici1974@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, CICIH RAHMAYANTI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "fitriantikharisma@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, FITRI KHARISMA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "nucke1972@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, NUCKE ANWAR Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "rerewae83@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, RERE WAE Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "imasku993@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, UMIH IMAS Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "lili.suherlina78@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, LILI SUHERLINA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "ferdinanugraha@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, FERDINA NUGRAHA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "windiwarsita4@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, WINDI WARSITA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "hardivilla07@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, HARDI VILLA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "rahmathid3421@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, RAHMAT HIDAYAT Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "fitriyahmaulana86@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, FITRIYAH MAULANA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "tenzbluepril@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, TENY BLUEPRIL Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "zuhriyyahfadhil@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ZUHRIYYAH FADHIL Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "mirna.saptiani@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, MIRNA SAPTIANI MIRNA SAPTIANI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "rosigusmantini@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ROSI GUSMANTINI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "fzahra44@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, FEBRILDA ZAHRA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "hasanahrinik@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, RINIK HASANAH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "attiaryati46@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ATTI  ARYATI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "armarifia45@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ARMA RIFIA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "elinnuraida4@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, ELIN NURAIDA Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "fahlevyrizky93@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, RIZKY FAHLEVY Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "martini50tini@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, MARTINI TINI Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "hendrayani35@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, BACKPACKER ESHAYE Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "uviuswatunh76@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, UVI HASANAH Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "utyagusriaty74@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, UTY AGUSRIATY Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;
case "salmisupriatin26@gmail.com":document.getElementById("demo").innerHTML = "<p style='font-size:18px ; color:black'>Selamat, SALMI SUPRIATIN Anda dinyatakan</p><p style='font-size:20px ; color:blue'>LULUS</p><p style='font-size:18px ; color:black'>E-Sertifikat masih dalam proses pengesahan</p>"; break;

case "":
document.getElementById("demo").innerHTML = "<p style='font-size:20px ; color:red'>Anda belum mengetikkan e-mail</p>"; break;

default:
    // code block
  document.getElementById("demo").innerHTML = "<p style='font-size:20px ; color:red'>e-mail Anda tidak terdaftar</p>";
  break;
}
} 
